enemy_color: "red"
# enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

# #####-----USB相机参数-----#####
# image_width: 1280
# image_height: 720
# fov_h: 57.7 #87.7
# fov_v: 56.7 
# new_fov_h: 27 #67
# new_fov_v: 40.9
# usb_frame_rate: 120
# usb_exposure: 500 #1-80000______250
# usb_gamma: 160
# usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "mindvision"
exposure_ms: 5
gain: 11.8
gamma: 0.41
vid_pid: "2bdf:0001"
wb_r: 100  # 手动白平衡R增益
wb_g: 100  # 手动白平衡G增益
wb_b: 100  # 手动白平衡B增益


#####-----传统方法参数-----#####
threshold: 150 #二值化阈值
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20 #同上长宽比
min_lightbar_length: 8 #最小长度
min_armor_ratio: 1 #小装甲板长宽比
max_armor_ratio: 5 #大装甲板长宽比
max_side_ratio: 1.5 #最大边长比
max_rectangular_error: 25 # 矩形度
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
serial_port: "/dev/ttyUSB0"
serial_baud: 115200

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"

#####-----tracker参数-----#####
min_detect_count: 4 #最小连续识别帧数
max_temp_lost_count: 25 #最大临时丢失帧数
outpost_max_temp_lost_count: 75 #前哨最大临时丢失帧数

#####-----aimer参数-----#####
yaw_offset: -2 # degree 偏置 (原-0.6偏左,右移0.9)
pitch_offset: 1.9 # degree (原2偏高,降低1.2)
comming_angle: 50
leaving_angle: 23
left_yaw_offset: 1 
right_yaw_offset: 1
decision_speed: 1.5 # rad/s 决策速度阈值
high_speed_delay_time: 0.083
low_speed_delay_time: 0.095  # s

#####-----shooter参数-----#####
first_tolerance: 0.5 # 近距离射击容差，degree
second_tolerance: 0.5 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

# #####-----planner-----#####
fire_thresh: 0.002

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----低通滤波参数-----#####
lpf_alpha: 0.68

####----方差----####
v1_base: 12 #加速度方差
v2_base: 14 #角速度方差
v1_outpost: 10
v2_outpost: 0.1

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [0, -1, 0, 1, 0, 0, 0, 0, 1]

#cameara
camera_matrix:   [1735.80692792, 0.00000000, 672.51975913, 0.00000000, 1739.00119057, 502.72252283, 0.00000000, 0.00000000, 1.00000000]
distort_coeffs:  [-0.08993843, 0.41924305, 0.00000000, 0.00000000, 0.00000000]

# 相机同理想情况的偏角
R_camera2gimbal: [0.02823004230930648, -0.014076983590428133, 0.99950232778328707, -0.99954530259354468, -0.010995644138609872, 0.028076393521179785, 0.010594940981141165, -0.99984045444409364, -0.014380990321749998]
t_camera2gimbal: [0.0032407000000000, 0.0565500000000000, -0.0662639000000000]

#####-----buff参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.600 # s
predict_time: 0.154 # s (原0.125提前量不够，增大)
